---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly3
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: firefly3-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        APP_KEY: "{{ .app_key }}"
        STATIC_CRON_TOKEN: "{{ .static_cron_token }}"
  dataFrom:
    - extract:
        key: firefly3
