---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-riki-boo
  annotations:
    gatus.home-operations.com/endpoint: |-
      url: https://echo.riki.boo/healthz
spec:
  hostnames:
    - echo.riki.boo
  parentRefs:
    - name: envoy-riki-boo-public
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: echo
          port: 80
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-brauni-dev
  annotations:
    gatus.home-operations.com/endpoint: |-
      url: https://echo.brauni.dev/healthz
spec:
  hostnames:
    - echo.brauni.dev
  parentRefs:
    - name: envoy-brauni-dev-public
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: echo
          port: 80
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-480p-com
  annotations:
    gatus.home-operations.com/endpoint: |-
      url: https://echo.480p.com/healthz
spec:
  hostnames:
    - echo.480p.com
  parentRefs:
    - name: envoy-480p-com-public
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: echo
          port: 80
