---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: databasus
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.60.0
    digest: sha256:88de3f85cc751ffa6eaa43afbb927893fbd521c17c0f710ce21b596d7ecdfe0a
  url: oci://ghcr.io/databasus/charts/databasus
