---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: databasus
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.58.0
    digest: sha256:e99f5ba25240be8177d15eca20defea4035fd92ec731912b67c417b634fde0b8
  url: oci://ghcr.io/databasus/charts/databasus
