---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: databasus
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.56.0
    digest: sha256:0e6538bf953d4e4b7b9a119e6a7be29aff12d761d7b0c045d40648a3f4b2f246
  url: oci://ghcr.io/databasus/charts/databasus
