---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: decypharr
spec:
  chartRef:
    kind: OCIRepository
    name: decypharr
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      decypharr:
        forceRename: decypharr
        annotations:
          reloader.stakater.com/auto: "true"
        # initContainers:
        #   setup-user:
        #     image:
        #       repository: cy01/blackhole
        #       tag: fenrir@sha256:e4378bc43d5607bb1a1118cb2a73d72b4e87edbeb44cad7fc7f2ba45a8488093
        #     command:
        #       - /bin/sh
        #       - -ec
        #       - |
        #         cp -a /etc/. /mnt/etc/
        #         grep -q '^decypharr:x:1000:1000:' /mnt/etc/passwd || echo 'decypharr:x:1000:1000:decypharr:/app:/sbin/nologin' >> /mnt/etc/passwd
        #         grep -q '^decypharr:x:1000:' /mnt/etc/group || echo 'decypharr:x:1000:' >> /mnt/etc/group
        #     securityContext:
        #       allowPrivilegeEscalation: false
        #       runAsGroup: 0
        #       runAsNonRoot: false
        #       runAsUser: 0
        #       capabilities: { drop: ["ALL"] }
        containers:
          app:
            image:
              repository: cy01/blackhole
              tag: beta@sha256:60aa997eb060a7e7e49cdccb31262c4d3d49b7564d31269eac1eb1fabd4795f1
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop: ["ALL"]
    service:
      app:
        forceRename: decypharr
        controller: decypharr
        ports:
          http:
            port: &port 8282
    persistence:
      app:
        existingClaim: decypharr
        globalMounts:
          - path: /app
      aio:
        type: emptyDir
        globalMounts:
          - path: /aio
      symlinks:
        existingClaim: symlinks
        globalMounts:
          - path: /aio/symlinks
      decypharr:
        type: custom
        volumeSpec:
          csi:
            driver: rclone.csi.veloxpack.io
            readOnly: true
            volumeAttributes:
              remote: decypharr
              remotePath: "/"
              dir-cache-time: "10s"
              vfs-cache-mode: full
              vfs-cache-max-age: "504h"
              vfs-cache-max-size: "10G"
              vfs-cache-poll-interval: "30s"
              vfs-read-chunk-size: "32M"
              vfs-read-chunk-size-limit: "128M"
              vfs-fast-fingerprint: "true"
              no-modtime: "true"
              no-checksum: "true"
              read-only: "true"
              configData: |
                [decypharr]
                type = webdav
                url = http://decypharr.media.svc.cluster.local:8282/webdav
                vendor = other
        globalMounts:
          - path: /aio/remote/realdebrid
            readOnly: true
      etc-userdb:
        type: emptyDir
        advancedMounts:
          decypharr:
            setup-user:
              - path: /mnt/etc
            app:
              - path: /etc
      tmp:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /tmp
