---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nzbdav
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: nzbdav-secret
    creationPolicy: Owner
  data:
    - secretKey: NZBDAV_USER
      remoteRef:
        key: /nzbdav/NZBDAV_USER
    - secretKey: NZBDAV_PASSWORD
      remoteRef:
        key: /nzbdav/NZBDAV_PASSWORD
    - secretKey: NZBDAV_API_KEY
      remoteRef:
        key: /nzbdav/NZBDAV_API_KEY
