---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP}-pg-backups
spec:
  schedule: 5 */12 * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          containers:
            - name: ${APP}-pg-backups
              image: docker.io/library/postgres:18
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - |-
                  set -euo pipefail
                  backup_file="/backup/${APP}-$(date +%Y%m%d-%H%M%S).sql.gz"
                  pg_dump -d "${APP}" | gzip -9 > "$${backup_file}"
                  find /backup -type f -name '${APP}-*.sql.gz' -mtime +7 -delete
              env:
                - name: PGHOST
                  value: ${CNPG_NAME:=postgres18}-rw.dbms.svc.cluster.local
                - name: PGPORT
                  value: "5432"
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      key: user
                      name: ${APP}-pguser-secret
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: ${APP}-pguser-secret
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: false
              volumeMounts:
                - mountPath: /backup
                  name: backups
          restartPolicy: OnFailure
          volumes:
            - name: backups
              persistentVolumeClaim:
                claimName: ${APP}-pg-backups
