---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-pg-backups
spec:
  sourcePVC: ${APP}-pg-backups
  trigger:
    schedule: ${VOLSYNC_TRIGGER_SCHEDULE:=0 */6 * * *}
  kopia:
    accessModes:
      - ${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    parallelism: 2
    repository: ${APP}-pg-backups-volsync-secret
    retain:
      hourly: 24
      daily: 7
    storageClassName: ${VOLSYNC_STORAGECLASS:=ceph-block}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}
