---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webdav-nfs
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  mountOptions:
    - port=2049
    - mountport=2049
    - tcp
    - nfsvers=3
  nfs:
    path: /
    server: 10.43.140.87
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webdav-nfs
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: webdav-nfs
