---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webdav-altmount
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  mountOptions:
    - port=2049
    - mountport=2049
    - tcp
    - nfsvers=3
  nfs:
    path: /
    server: webdav-nfs-gateway.media.svc.cluster.local
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webdav-altmount
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: webdav-altmount
