---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: comet
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: comet-secret
    creationPolicy: Owner
    template:
      data:
        ADMIN_DASHBOARD_PASSWORD: "{{ .ADMIN_DASHBOARD_PASSWORD }}"
  dataFrom:
    - extract:
        key: comet
