---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: alertmanager-secret
    template:
      data:
        ALERTMANAGER_PUSHOVER_TOKEN: "{{ .ALERTMANAGER_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  data:
    - secretKey: ALERTMANAGER_PUSHOVER_TOKEN
      remoteRef:
        key: /alertmanager/ALERTMANAGER_PUSHOVER_TOKEN
    - secretKey: PUSHOVER_USER_KEY
      remoteRef:
        key: /pushover/PUSHOVER_USER_KEY
