---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel-brauni-dev
  annotations:
    dns.scope: cloudflare
spec:
  endpoints:
    - dnsName: public.brauni.dev
      recordType: CNAME
      targets:
        - ${CLOUDFLARE_TUNNEL_BRAUNI_DEV_ID}.cfargotunnel.com
