---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warrden
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: warrden-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          logLevel: info

          instances:
            - type: radarr
              enabled: true
              name: Radarr
              url: http://radarr.media.svc.cluster.local
              apiVersion: v3
              apiKey: "{{ .API_KEY }}"
              missingSearch:
                enabled: true
                cron: "*/15 * * * *"
                maxResults: 15
                cooldown: 7d
              upgradeSearch:
                enabled: true
                cron: "*/15 * * * *"
                maxResults: 15
                cooldown: 7d
              queueCleanup:
                enabled: true
                cron: "* * * * *"

            - type: radarr
              enabled: true
              name: Radarr4K
              url: http://radarr4k.media.svc.cluster.local
              apiVersion: v3
              apiKey: "{{ .API_KEY }}"
              missingSearch:
                enabled: true
                cron: "*/15 * * * *"
                maxResults: 15
                cooldown: 7d
              upgradeSearch:
                enabled: true
                cron: "*/15 * * * *"
                maxResults: 15
                cooldown: 7d
              queueCleanup:
                enabled: true
                cron: "* * * * *"

            - type: sonarr
              enabled: true
              name: Sonarr
              url: http://sonarr.media.svc.cluster.local
              apiVersion: v3
              apiKey: "{{ .API_KEY }}"
              missingSearch:
                enabled: true
                searchType: episode
                cron: "*/15 * * * *"
                maxResults: 15
                cooldown: 7d
              upgradeSearch:
                enabled: true
                searchType: season
                cron: "*/15 * * * *"
                maxResults: 1
                cooldown: 7d
              queueCleanup:
                enabled: true
                cron: "* * * * *"

            - type: sonarr
              enabled: true
              name: Sonarr4K
              url: http://sonarr4k.media.svc.cluster.local
              apiVersion: v3
              apiKey: "{{ .API_KEY }}"
              missingSearch:
                enabled: true
                searchType: episode
                cron: "*/15 * * * *"
                maxResults: 15
                cooldown: 7d
              upgradeSearch:
                enabled: true
                searchType: season
                cron: "*/15 * * * *"
                maxResults: 1
                cooldown: 7d
              queueCleanup:
                enabled: true
                cron: "* * * * *"

          queueCleanupRules:
            radarr:
              - match: SAMPLE
                action: removeAndBlocklist
              - match: NO_FILES_ELIGIBLE
                action: removeAndBlocklist
              - match: MATCHED_VIA_GRAB_HISTORY
                action: removeAndBlocklist
              - match: NOT_IN_GRABBED_RELEASE
                action: removeAndBlocklist
              - match: NOT_QUALITY_UPGRADE
                action: remove
              - match: NOT_REVISION_UPGRADE
                action: remove
              - match: NOT_CUSTOM_FORMAT_UPGRADE
                action: remove
              - match: MOVIE_ALREADY_IMPORTED
                action: remove
              - match: NO_AUDIO_TRACKS
                action: removeAndBlocklist
              - match: ARCHIVE_FILE
                action: removeAndBlocklist
              - match: INSUFFICIENT_FREE_SPACE
                action: removeAndBlocklist
              - match: FILE_UNPACKING
                action: remove
              - match: UNABLE_TO_PARSE
                action: none
              - match: UNEXPECTED_ERROR
                action: none
              - match: LOCKED_FILE
                action: none
              - match: UNSUPPORTED_EXTENSION
                action: none
              - match: DANGEROUS_FILE
                action: none
              - match: DOWNLOAD_CLIENT_ERROR
                action: none
              - match: IMPORT_PATH_INACCESSIBLE
                action: none

            sonarr:
              - match: SAMPLE
                action: removeAndBlocklist
              - match: NO_FILES_ELIGIBLE
                action: removeAndBlocklist
              - match: MATCHED_VIA_GRAB_HISTORY
                action: removeAndBlocklist
              - match: NOT_IN_GRABBED_RELEASE
                action: removeAndBlocklist
              - match: EPISODE_UNEXPECTED_FOLDER
                action: removeAndBlocklist
              - match: FULL_SEASON_PACK
                action: removeAndBlocklist
              - match: NOT_QUALITY_UPGRADE
                action: remove
              - match: NOT_REVISION_UPGRADE
                action: remove
              - match: NOT_CUSTOM_FORMAT_UPGRADE
                action: remove
              - match: INVALID_SEASON_OR_EPISODE
                action: removeAndBlocklist
              - match: EPISODE_ALREADY_IMPORTED
                action: remove
              - match: NO_AUDIO_TRACKS
                action: removeAndBlocklist
              - match: ARCHIVE_FILE
                action: removeAndBlocklist
              - match: INSUFFICIENT_FREE_SPACE
                action: removeAndBlocklist
              - match: FILE_UNPACKING
                action: remove
              - match: UNABLE_TO_PARSE
                action: none
              - match: UNEXPECTED_ERROR
                action: none
              - match: LOCKED_FILE
                action: none
              - match: UNSUPPORTED_EXTENSION
                action: none
              - match: DANGEROUS_FILE
                action: none
              - match: DOWNLOAD_CLIENT_ERROR
                action: none
              - match: IMPORT_PATH_INACCESSIBLE
                action: none
              - match: TITLE_MISSING
                action: none
              - match: TITLE_TBA
                action: none
              - match: EXISTING_FILE_MORE_EPISODES
                action: none
              - match: SPLIT_EPISODE
                action: none
              - match: MISSING_ABSOLUTE_NUMBER
                action: none
              - match: UNVERIFIED_SCENE_MAPPING
                action: none
  data:
    - secretKey: API_KEY
      remoteRef:
        key: /servarr/API_KEY
