---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app warrden
spec:
  chartRef:
    kind: OCIRepository
    name: warrden
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
    controllers:
      warrden:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: code.neureka.dev/warrden/warrden
              tag: 4.1.3@sha256:5efe2bc6f5eccdd764cf08b89f4d8712b201d570adb52c4d45a64010a1fe4b15
            env:
              PUID: "1000"
              PGID: "1000"
              CONFIG_PATH: /app/data/config.yaml
              DATABASE_PATH: /app/data/warrden.db
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      data:
        existingClaim: warrden
        globalMounts:
          - path: /app/data
      config:
        type: secret
        name: warrden-secret
        globalMounts:
          - path: /app/data/config.yaml
            subPath: config.yaml
            readOnly: true
