---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app warrden
spec:
  chartRef:
    kind: OCIRepository
    name: warrden
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
    controllers:
      warrden:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/neurekadev/warrden
              tag: 5.1.0@sha256:36ff2b05abb7ee28af3731081ecf3434f3a860e2aec9d8bf68c664355a51b63a
            env:
              PUID: "1000"
              PGID: "1000"
              CONFIG_PATH: /config/config.yaml
              DATABASE_PATH: /app/data/warrden.db
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            securityContext:
              capabilities:
                drop:
                  - NET_RAW
    persistence:
      data:
        existingClaim: warrden
        globalMounts:
          - path: /app/data
      config:
        type: secret
        name: warrden-secret
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
