---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./bitmagnet/ks.yaml
  - ./booklore/ks.yaml
  - ./cleanuparr/ks.yaml
  # - ./comet/ks.yaml
  - ./decypharr/ks.yaml
  - ./media-debug/ks.yaml
  - ./newtarr/ks.yaml
  - ./plex/ks.yaml
  - ./profilarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr4k/ks.yaml
  - ./seerr/ks.yaml
  - ./shelfmark/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr4k/ks.yaml
  - ./stremthru/ks.yaml
  # - ./swaparr/ks.yaml
  - ./symlinks/ks.yaml
