---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./symlinks/ks.yaml
  # - ./aio/rclone/ks.yaml
  - ./decypharr/ks.yaml
  - ./plex/ks.yaml
  - ./booklore/ks.yaml
  - ./shelfmark/ks.yaml
  - ./media-debug/ks.yaml
