---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app symlinks
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: bitwarden
      namespace: external-secrets
    - name: volsync
      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/media/symlinks/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_STORAGECLASS: ceph-filesystem
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-filesystem
      VOLSYNC_SNAP_ACCESSMODES: ReadOnlyMany
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
