---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: sonarr4k
  annotations:
    dns.scope: all
spec:
  endpoints:
    - dnsName: sonarr4k.brauni.dev
      recordType: CNAME
      targets:
        - public.brauni.dev
    - dnsName: sonarr4k.riki.boo
      recordType: CNAME
      targets:
        - public.riki.boo
