---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app umlautadaptarrex
spec:
  chartRef:
    kind: OCIRepository
    name: umlautadaptarrex
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    controllers:
      umlautadaptarrex:
        containers:
          app:
            image:
              repository: lexfi/umlautadaptarrex
              tag: 1.2.4@sha256:29897b0157a3f0c8577e5a4b083368b1eeee119e5643e2e45b169752efe9db67
            env:
              PUID: "1000"
              PGID: "1000"
              LOG_LEVEL: info
              PORT: &apiPort 5005
              WEB_PORT: &webPort 5007
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: *apiPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: *apiPort
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETUID
                  - SETGID
    service:
      app:
        controller: umlautadaptarrex
        ports:
          http:
            port: *webPort
          api:
            port: *apiPort
          proxy:
            port: 5006
    persistence:
      data:
        existingClaim: umlautadaptarrex
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
