---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_EMAIL__HOST: "{{ .AUTHENTIK_EMAIL__HOST }}"
        AUTHENTIK_EMAIL__PORT: "{{ .AUTHENTIK_EMAIL__PORT }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .AUTHENTIK_EMAIL__USERNAME }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .AUTHENTIK_EMAIL__PASSWORD }}"
        AUTHENTIK_EMAIL__USE_TLS: "{{ .AUTHENTIK_EMAIL__USE_TLS }}"
        AUTHENTIK_EMAIL__USE_SSL: "{{ .AUTHENTIK_EMAIL__USE_SSL }}"
        AUTHENTIK_EMAIL__FROM: "{{ .AUTHENTIK_EMAIL__FROM }}"
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: /authentik/AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_EMAIL__HOST
      remoteRef:
        key: /authentik/AUTHENTIK_EMAIL__HOST
    - secretKey: AUTHENTIK_EMAIL__PORT
      remoteRef:
        key: /authentik/AUTHENTIK_EMAIL__PORT
    - secretKey: AUTHENTIK_EMAIL__USERNAME
      remoteRef:
        key: /authentik/AUTHENTIK_EMAIL__USERNAME
    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: /authentik/AUTHENTIK_EMAIL__PASSWORD
    - secretKey: AUTHENTIK_EMAIL__USE_TLS
      remoteRef:
        key: /authentik/AUTHENTIK_EMAIL__USE_TLS
    - secretKey: AUTHENTIK_EMAIL__USE_SSL
      remoteRef:
        key: /authentik/AUTHENTIK_EMAIL__USE_SSL
    - secretKey: AUTHENTIK_EMAIL__FROM
      remoteRef:
        key: /authentik/AUTHENTIK_EMAIL__FROM
