---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./serviceaccount.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./dnsendpoints.yaml
  - ./referencegrant.yaml
configMapGenerator:
  - name: authentik-blueprints
    files:
      - forward-auth.yaml=./blueprints/forward-auth.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
