---
# yaml-language-server: $schema=https://json.schemastore.org/kube-1.31/jsonschema/k8s.io/kubernetes/namespace_v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: _
  labels:
    # virt-launcher and cdi-importer pods running in this namespace
    # require privileged Pod Security.
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.35
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.35
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.35
