---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: "${APP}-volsync-secret"
    template:
      data:
        KOPIA_REPOSITORY: "{{ .KOPIA_REPOSITORY }}"
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        SFTP_HOST: "{{ .SFTP_HOST }}"
        SFTP_PORT: "{{ .SFTP_PORT }}"
        SFTP_USERNAME: "{{ .SFTP_USERNAME }}"
        SFTP_PATH: "{{ .SFTP_PATH }}"
        SFTP_KEY_FILE: "{{ .SFTP_KEY_FILE }}"
        SFTP_KNOWN_HOSTS_DATA: "{{ .SFTP_KNOWN_HOSTS_DATA }}"
  data:
    - secretKey: KOPIA_REPOSITORY
      remoteRef:
        key: /volsync-template/KOPIA_REPOSITORY
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: /volsync-template/KOPIA_PASSWORD
    - secretKey: SFTP_HOST
      remoteRef:
        key: /volsync-template/SFTP_HOST
    - secretKey: SFTP_PORT
      remoteRef:
        key: /volsync-template/SFTP_PORT
    - secretKey: SFTP_USERNAME
      remoteRef:
        key: /volsync-template/SFTP_USERNAME
    - secretKey: SFTP_PATH
      remoteRef:
        key: /volsync-template/SFTP_PATH
    - secretKey: SFTP_KEY_FILE
      remoteRef:
        key: /volsync-template/SFTP_KEY_FILE
    - secretKey: SFTP_KNOWN_HOSTS_DATA
      remoteRef:
        key: /kopia_known_hosts/SFTP_KNOWN_HOSTS_DATA
