---
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: ${APP}
spec:
  repository:
    repository: ${APP}-volsync-secret
  enabled: true
  trigger:
    schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 2Gi
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: ${VOLSYNC_PUID:=1000}
    runAsGroup: ${VOLSYNC_PGID:=1000}
    fsGroup: ${VOLSYNC_PGID:=1000}
    fsGroupChangePolicy: OnRootMismatch
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
