---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/v1/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retrieval-deps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
