---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-altmount
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: rclone-altmount-secret
    creationPolicy: Owner
    template:
      data:
        RCLONE_CONFIG_ALTMOUNT_USER: "{{ .user }}"
        RCLONE_CONFIG_ALTMOUNT_PASS: "{{ .pass }}"
  data:
    - secretKey: user
      remoteRef:
        key: /rclone/user
    - secretKey: pass
      remoteRef:
        key: /rclone/pass
