---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: altmount
spec:
  chartRef:
    kind: OCIRepository
    name: altmount
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      altmount:
        forceRename: altmount
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/drondeseries/altmount
              tag: dev@sha256:3152eeec182d30c2297b73ad0b4735f58cfd30de5ec6e729b353dfab38eb5088
            env:
              PUID: "1000"
              PGID: "1000"
              PORT: &port 8080
              JWT_SECRET: YrIH4W7v4dpC7SiDd6l+CFdHdYGumEHwH/pd54QKhSg=
              COOKIE_DOMAIN: altmount.480p.com
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              privileged: true
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
    service:
      app:
        forceRename: altmount
        controller: altmount
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: altmount
        globalMounts:
          - path: /config
      aio:
        type: emptyDir
        globalMounts:
          - path: /aio
      symlinks:
        existingClaim: symlinks
        globalMounts:
          - path: /aio/symlinks
      fuse:
        type: hostPath
        hostPath: /dev/fuse
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/fuse
      tmp:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /tmp
