---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: altmount
spec:
  chartRef:
    kind: OCIRepository
    name: altmount
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      altmount:
        forceRename: altmount
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/javi11/altmount
              tag: v0.2.0@sha256:2592723a519248340e43fa5a564cff01f3faf24f680ba4d8a1ae84f2e87c2cd2
            args:
              - serve
              - --config=/config/config.yaml
            env:
              PUID: "1000"
              PGID: "1000"
              PORT: &port 8080
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop: ["ALL"]
    service:
      app:
        forceRename: altmount
        controller: altmount
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: altmount
        globalMounts:
          - path: /config
      symlinks:
        existingClaim: symlinks
        globalMounts:
          - path: /aio/symlinks
      tmp:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /tmp
