---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: litellm-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        LITELLM_SALT_KEY: "{{ .LITELLM_SALT_KEY }}"
        ZAI_API_KEY: "{{ .ZAI_API_KEY }}"
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: /litellm/LITELLM_MASTER_KEY
    - secretKey: LITELLM_SALT_KEY
      remoteRef:
        key: /litellm/LITELLM_SALT_KEY
    - secretKey: ZAI_API_KEY
      remoteRef:
        key: /litellm/ZAI_API_KEY
