---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: swaparr
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: swaparr-secret
    creationPolicy: Owner
    template:
      data:
        RADARR_APIKEY: "{{ .API_KEY }}"
        RADARR4K_APIKEY: "{{ .API_KEY }}"
        SONARR_APIKEY: "{{ .API_KEY }}"
        SONARR4K_APIKEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: servarr
