---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
  driftDetection:
    mode: enabled
  values:
    manager:
      extraArgs:
        - --metrics-bind-address=0.0.0.0:8080
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
      grafanaOperator:
        enabled: true
        matchLabels:
          grafana.internal/instance: grafana
