---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: idlers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: idlers-secret
    template:
      data:
        DB_HOST: "{{ .DB_HOST }}"
        DB_DATABASE: "{{ .DB_DATABASE }}"
        DB_USERNAME: "{{ .DB_USERNAME }}"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        MYSQL_ROOT_PASSWORD: "{{ .MYSQL_ROOT_PASSWORD }}"
        MYSQL_USER: "{{ .MYSQL_USER }}"
        MYSQL_PASSWORD: "{{ .MYSQL_PASSWORD }}"
        MYSQL_DATABASE: "{{ .MYSQL_DATABASE }}"
  dataFrom:
    - extract:
        key: idlers
