---
libraries:
  Movies:
    schedule: hourly(6),hourly(18)
    refresh_metadata: true
    overlay_files:
      - remove_overlays: false
      - file: config/overlays.yml
        template_variables:
          4K: true
          4K-HDR: true
          4K-Dolby: true
          4K-Episode: false
  TV Shows:
    schedule: hourly(6),hourly(18)
    refresh_metadata: true
    overlay_files:
      - remove_overlays: false
      - file: config/overlays.yml
        template_variables:
          4K: true
          4K-HDR: true
          4K-Dolby: true
          4K-Episode: true

settings:
  cache: true
  cache_expiration: 60
  sync_mode: sync
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: true
  run_again_delay: 2
  asset_directory: /config/assets
  show_unconfigured: true

plex:
  url: http://plex.media.svc.cluster.local:32400
  token: env
  timeout: 120

tmdb:
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60

omdb:
  apikey: <<OMDB_API_KEY>>
  cache_expiration: 60

trakt:
  client_id: <<TRAKT_CLIENT_ID>>
  client_secret: <<TRAKT_CLIENT_SECRET>>
  authorization:
    access_token: <<TRAKT_ACCESS_TOKEN>>
    token_type: Bearer
    expires_in: <<TRAKT_EXPIRES_IN>>
    refresh_token: <<TRAKT_REFRESH_TOKEN>>
    scope: public
    created_at: <<TRAKT_CREATED_AT>>
