---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./csi-rclone-grafanadashboard.yaml
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./proxmox-grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: proxmox-observability-dashboard
    files:
      - proxmox-observability.json=./resources/proxmox-observability.json
  - name: proxmox-logs-dashboard
    files:
      - proxmox-logs.json=./resources/proxmox-logs.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
