---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cdi.kubevirt.io/storageprofile_v1beta1.json
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: ceph-block-kubevirt
spec:
  claimPropertySets:
    - accessModes:
        - ReadWriteMany
      volumeMode: Block
