---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app networking-toolbox
spec:
  chartRef:
    kind: OCIRepository
    name: networking-toolbox
  interval: 30m
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    controllers:
      networking-toolbox:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/lissy93/networking-toolbox
              tag: 1.6.0@sha256:4e97330fb310e1a5fbe185b1bf859270902ddef7934b88cecc6b3def98d21eaa
            env:
              PORT: "3000"
              HOST: 0.0.0.0
              NODE_ENV: production
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: networking-toolbox
        primary: true
        ports:
          http:
            port: 3000

    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
            url: https://net-tools.brauni.dev/health
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Tools
          gethomepage.dev/name: Networking Toolbox
          gethomepage.dev/pod-selector: app.kubernetes.io/name=networking-toolbox
          gethomepage.dev/icon: mdi-lan
        hostnames:
          - networking-toolbox.brauni.dev
          - net-tools.brauni.dev
        parentRefs:
          - name: envoy-brauni-dev-public
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: 3000

    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
