---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-exporter
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: proxmox-exporter-secret
    creationPolicy: Owner
    template:
      data:
        PVE_HOST: "{{ .PVE_HOST }}"
        PVE_USER: "{{ .PVE_USER }}"
        PVE_TOKEN_NAME: "{{ .PVE_TOKEN_NAME }}"
        PVE_TOKEN_VALUE: "{{ .PVE_TOKEN_VALUE }}"
  dataFrom:
    - extract:
        key: proxmox-exporter
