---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-exporter
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: proxmox-exporter-secret
    creationPolicy: Owner
    template:
      data:
        PVE_HOST: "{{ .PVE_HOST }}"
        PVE_USER: "{{ .PVE_USER }}"
        PVE_TOKEN_NAME: "{{ .PVE_TOKEN_NAME }}"
        PVE_TOKEN_VALUE: "{{ .PVE_TOKEN_VALUE }}"
  data:
    - secretKey: PVE_HOST
      remoteRef:
        key: /proxmox-exporter/PVE_HOST
    - secretKey: PVE_USER
      remoteRef:
        key: /proxmox-exporter/PVE_USER
    - secretKey: PVE_TOKEN_NAME
      remoteRef:
        key: /proxmox-exporter/PVE_TOKEN_NAME
    - secretKey: PVE_TOKEN_VALUE
      remoteRef:
        key: /proxmox-exporter/PVE_TOKEN_VALUE
