---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: proxmox-exporter
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      proxmox-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/prompve/prometheus-pve-exporter
              tag: 3.8.1
            env:
              PVE_VERIFY_SSL: "true"
            envFrom:
              - secretRef:
                  name: proxmox-exporter-secret
            probes:
              liveness: &httpProbe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /metrics
                    port: &port 9221
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *httpProbe
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    service:
      app:
        ports:
          metrics:
            port: *port
