---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  chartRef:
    kind: OCIRepository
    name: immich
  interval: 30m
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      immich:
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: immich-secret,immich-pguser-secret
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "18"
            envFrom:
              - secretRef:
                  name: immich-initdb-secret
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.5.6
            env:
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: &pguser immich-pguser-secret
                    key: user
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *pguser
                    key: password
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: *pguser
                    key: db
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: *pguser
                    key: host
              DB_PORT:
                valueFrom:
                  secretKeyRef:
                    name: *pguser
                    key: port
            envFrom: &envFrom
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 4Gi

      machine-learning:
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: immich-secret
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.5.6
            env:
              MACHINE_LEARNING_CACHE_FOLDER: /cache
              TRANSFORMERS_CACHE: /cache
            envFrom: *envFrom
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 8Gi

    service:
      immich:
        primary: true
        controller: immich
        ports:
          http:
            port: &port 2283
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003

    route:
      app:
        hostnames:
          - immich.brauni.dev
        parentRefs:
          - name: envoy-brauni-dev-public
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: immich
                port: http

    persistence:
      data:
        existingClaim: immich
        advancedMounts:
          immich:
            app:
              - path: /usr/src/app/upload
      machine-learning-cache:
        existingClaim: immich-machine-learning-cache
        advancedMounts:
          machine-learning:
            app:
              - path: /cache
              - path: /.cache
                subPath: dot-cache
