---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app clonarr
spec:
  chartRef:
    kind: OCIRepository
    name: clonarr
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
    controllers:
      clonarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/prophetse7en/clonarr
              tag: v2.5.6@sha256:8cfc257d94f018f25a03eadf5d3aae9f1a4470f3cb25e0cf00eb0d60f532c67d
            env:
              PORT: &port 6060
              PUID: "1000"
              PGID: "1000"
            probes:
              liveness: &probes
                enabled: true
                spec:
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              runAsUser: 0
              runAsGroup: 0
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETUID
                  - SETGID
    service:
      app:
        controller: clonarr
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: clonarr
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
