---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: gatus-secret
    template:
      data:
        GATUS_TINYAUTH_BASIC_AUTH: "{{ .GATUS_TINYAUTH_BASIC_AUTH }}"
  data:
    - secretKey: GATUS_TINYAUTH_BASIC_AUTH
      remoteRef:
        key: /gatus/GATUS_TINYAUTH_BASIC_AUTH
