---
# yaml-language-server: $schema=https://json.schemastore.org/kube-1.31/jsonschema/k8s.io/kubernetes/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdi-operator
  namespace: cdi
spec:
  template:
    spec:
      containers:
        - name: cdi-operator
          image: quay.io/kubevirt/cdi-operator:v1.66.0@sha256:45964f62a027e09463c8dd48a2cbaf063c0afe771edb18e505f4461d0915984c
          env:
            - name: CONTROLLER_IMAGE
              value: quay.io/kubevirt/cdi-controller:v1.66.0@sha256:6541d5b148731bd895bf7b3c1702745a91e5d28d7f84d9a24bf12cf9ddf73e97
            - name: IMPORTER_IMAGE
              value: quay.io/kubevirt/cdi-importer:v1.66.0@sha256:a8bcb878c82012e1a2dd1bbeda473e00a68a2ad2aa510ea86ec45c7bc53e0564
            - name: CLONER_IMAGE
              value: quay.io/kubevirt/cdi-cloner:v1.66.0@sha256:f827669046899a22e2c22d284b4e2d2be7c4fe84718a79446bb3b5376a01a963
            - name: OVIRT_POPULATOR_IMAGE
              value: quay.io/kubevirt/cdi-importer:v1.66.0@sha256:a8bcb878c82012e1a2dd1bbeda473e00a68a2ad2aa510ea86ec45c7bc53e0564
            - name: APISERVER_IMAGE
              value: quay.io/kubevirt/cdi-apiserver:v1.66.0@sha256:b91ab8a39fac74f9035c9ebbe2da6f8499073215180b5fc47c924a5c14e57d37
            - name: UPLOAD_SERVER_IMAGE
              value: quay.io/kubevirt/cdi-uploadserver:v1.66.0@sha256:3b425f6f2fa85a24c048f4681ad17a5b3cc083f3674df7b918087d2e0816ac1b
            - name: UPLOAD_PROXY_IMAGE
              value: quay.io/kubevirt/cdi-uploadproxy:v1.66.0@sha256:e7a56580955dee3f35133365630ac45009428101f3de003e227bfdf61d32d9b0
            - name: MONITORING_NAMESPACE
              value: observability
