---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app profilarr
spec:
  chartRef:
    kind: OCIRepository
    name: profilarr
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
    controllers:
      profilarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: santiagosayshey/profilarr
              tag: beta@sha256:864486f403195b2ae3277335ac46457db587de983c5a1814c93bb384a0d3252c
            env:
              LOG_LEVEL: info
              PORT: &port 6868
              PGID: "1000"
              PUID: "1000"
            probes:
              liveness: &probes
                enabled: true
                spec:
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              runAsUser: 0
              runAsGroup: 0
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETUID
                  - SETGID
    service:
      app:
        controller: profilarr
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: profilarr
        globalMounts:
          - path: /config
            subPath: config
      tmp:
        type: emptyDir
