---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-sftp-config
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kopiur-sftp-config
    template:
      engineVersion: v2
      data:
        SFTP_HOST: "{{ .SFTP_HOST }}"
        SFTP_PORT: "{{ .SFTP_PORT }}"
        SFTP_USERNAME: "{{ .SFTP_USERNAME }}"
        SFTP_PATH: "{{ .SFTP_PATH }}"
  data:
    - secretKey: SFTP_HOST
      remoteRef:
        key: /volsync-template/SFTP_HOST
    - secretKey: SFTP_PORT
      remoteRef:
        key: /volsync-template/SFTP_PORT
    - secretKey: SFTP_USERNAME
      remoteRef:
        key: /volsync-template/SFTP_USERNAME
    - secretKey: SFTP_PATH
      remoteRef:
        key: /volsync-template/SFTP_PATH
