---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: homepage
  annotations:
    dns.scope: all
spec:
  endpoints:
    - dnsName: homepage.brauni.dev
      recordType: CNAME
      targets:
        - public.brauni.dev
    - dnsName: home.brauni.dev
      recordType: CNAME
      targets:
        - public.brauni.dev
    - dnsName: homepage.riki.boo
      recordType: CNAME
      targets:
        - public.riki.boo
    - dnsName: home.riki.boo
      recordType: CNAME
      targets:
        - public.riki.boo
    - dnsName: homepage.480p.com
      recordType: CNAME
      targets:
        - public.480p.com
    - dnsName: home.480p.com
      recordType: CNAME
      targets:
        - public.480p.com
