---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_PATCHMON_AUTH_HEADER: "Basic {{ .PATCHMON_API_KEY }}"
  dataFrom:
    - extract:
        key: homepage
