---
# yaml-language-server: $schema=https://json.schemastore.org/kube-1.31/jsonschema/k8s.io/kubernetes/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virt-operator
  namespace: kubevirt
spec:
  template:
    spec:
      containers:
        - name: virt-operator
          image: quay.io/kubevirt/virt-operator:v1.8.4@sha256:65d23c9ad91707a4fb5f0103e04c12d02343437ac44e3a31608d7a1fff003d55
          env:
            - name: VIRT_OPERATOR_IMAGE
              value: quay.io/kubevirt/virt-operator:v1.8.4@sha256:65d23c9ad91707a4fb5f0103e04c12d02343437ac44e3a31608d7a1fff003d55
            - name: VIRT_API_IMAGE
              value: quay.io/kubevirt/virt-api:v1.8.4@sha256:8df9c3b10cafbca3bbd8d42f005f12abed14ec70c9f1feea209d5785618db028
            - name: VIRT_CONTROLLER_IMAGE
              value: quay.io/kubevirt/virt-controller:v1.8.4@sha256:4135c3f1284aadb60b914b50cbf3be6be3d2d14a050ada2397cc89b47c525e4e
            - name: VIRT_HANDLER_IMAGE
              value: quay.io/kubevirt/virt-handler:v1.8.4@sha256:d6b8f966f7f8cc032821d8c5d62507056381c739c886e3aa547482fb1ac6f6b0
            - name: VIRT_LAUNCHER_IMAGE
              value: quay.io/kubevirt/virt-launcher:v1.8.4@sha256:c89f733b1fdcc810d0b4326bbfc652a4cf3d25bc56cc8545f124d5cb71a1ce20
            - name: VIRT_EXPORTPROXY_IMAGE
              value: quay.io/kubevirt/virt-exportproxy:v1.8.4@sha256:ef68bb9b9f997d4aca56a8053cc368a5eeb2d9623de5fed3356e7ce4f38290e2
            - name: VIRT_EXPORTSERVER_IMAGE
              value: quay.io/kubevirt/virt-exportserver:v1.8.4@sha256:1489c5ee739a24a24fdaa0a96b4ea1336ebbcbcadd5f04deb2ca96c47a8a6e6a
            - name: VIRT_SYNCHRONIZATIONCONTROLLER_IMAGE
              value: quay.io/kubevirt/virt-synchronization-controller:v1.8.4@sha256:631ade5aced9ffb248f2725759c7d37376d596875b05f6a331a12342a281a1ce
            - name: PR_HELPER_IMAGE
              value: quay.io/kubevirt/pr-helper:v1.8.4@sha256:eca8d1f2c46ce09c18d4e59a44276ef4f02bea82665a6525aed8b5f76986131a
            - name: SIDECAR_SHIM_IMAGE
              value: quay.io/kubevirt/sidecar-shim:v1.8.4@sha256:95255857aa7ea1924f6742534707930f452e46242c8ab7d5570d297ed89a34b0
