---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: radarr-secret
    creationPolicy: Owner
    template:
      data:
        RADARR__AUTH__APIKEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: servarr
