---
apiVersion: v1
kind: Pod
metadata:
  name: aws-debug
spec:
  restartPolicy: Always
  containers:
    - name: aws-cli
      image: amazon/aws-cli:2.34.11@sha256:2aba3b77ff0d8b90a675973b2773188bf175e387856bdb54a4ea14aa76c47fbb
      command:
        - sleep
        - infinity
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: cnpg-backups
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cnpg-backups
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_ENDPOINT_URL_S3
          value: http://rook-ceph-rgw-proxmox-s3.rook-ceph.svc:80
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
