---
apiVersion: v1
kind: Pod
metadata:
  name: aws-debug
spec:
  restartPolicy: Always
  containers:
    - name: aws-cli
      image: amazon/aws-cli:2.34.52@sha256:d12f97286c70c50dafa3313fe6b6dc3aefd5dd71e0a73f3f893ea181aad2bdf8
      command:
        - sleep
        - infinity
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: cnpg-backups
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cnpg-backups
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_ENDPOINT_URL_S3
          value: http://rook-ceph-rgw-proxmox-s3.rook-ceph.svc:80
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
