---
apiVersion: v1
kind: Pod
metadata:
  name: aws-debug
spec:
  restartPolicy: Always
  containers:
    - name: aws-cli
      image: amazon/aws-cli:2.34.29@sha256:a21c9fdf2ae8427b79d93d5a618aea12068da4864bd58072fa5436fd0ca9539d
      command:
        - sleep
        - infinity
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: cnpg-backups
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cnpg-backups
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_ENDPOINT_URL_S3
          value: http://rook-ceph-rgw-proxmox-s3.rook-ceph.svc:80
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
