---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.3-1.1.1
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - vchord.so
    parameters:
      max_connections: "400"
      max_locks_per_transaction: "128"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      memory: 12Gi
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://cnpg-backups/immich/v2/
      endpointURL: http://rook-ceph-rgw-proxmox-s3.rook-ceph.svc:80
      s3Credentials:
        accessKeyId:
          name: cnpg-backups
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backups
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
        maxParallel: 8
