---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./aws-debug.yaml
  - ./cluster18.yaml
  - ./cnpg-backups-obc.yaml
  - ./grafanadashboard.yaml
  - ./immich.yaml
  - ./pgdumpall.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
