---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./homepage/ks.yaml
  - ./opencloud/ks.yaml
  - ./open-webui/ks.yaml
  - ./web-check/ks.yaml
  - ./karakeep/ks.yaml
  - ./idlers/ks.yaml
  - ./immich/ks.yaml
  - ./atuin/ks.yaml
  - ./jotty/ks.yaml
  - ./bentopdf/ks.yaml
  - ./firefly3/ks.yaml
  - ./paperless/ks.yaml
  - ./patchmon/ks.yaml
