---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: kometa-secret
    creationPolicy: Owner
    template:
      data:
        KOMETA_PLEX_URL: "{{ .PLEX_URL }}"
        KOMETA_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        KOMETA_TMDB_API_KEY: "{{ .TMDB_API_KEY }}"
        KOMETA_OMDB_API_KEY: "{{ .OMDB_API_KEY }}"
        KOMETA_TRAKT_CLIENT_ID: "{{ .TRAKT_CLIENT_ID }}"
        KOMETA_TRAKT_CLIENT_SECRET: "{{ .TRAKT_CLIENT_SECRET }}"
        KOMETA_TRAKT_ACCESS_TOKEN: "{{ .TRAKT_ACCESS_TOKEN }}"
        KOMETA_TRAKT_REFRESH_TOKEN: "{{ .TRAKT_REFRESH_TOKEN }}"
        KOMETA_TRAKT_EXPIRES_IN: "{{ .TRAKT_EXPIRES_IN }}"
        KOMETA_TRAKT_CREATED_AT: "{{ .TRAKT_CREATED_AT }}"
  dataFrom:
    - extract:
        key: kometa
    - extract:
        key: bitmagnet