---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: kometa-secret
    creationPolicy: Owner
    template:
      data:
        PLEX_URL: "{{ index . \"PLEX_URL\" | default \"http://plex.media.svc.cluster.local:32400\" }}"
        PLEX_TOKEN: "{{ index . \"PLEX_TOKEN\" | default \"\" }}"
        TMDB_API_KEY: "{{ index . \"TMDB_API_KEY\" | default \"\" }}"
        OMDB_API_KEY: "{{ index . \"OMDB_API_KEY\" | default \"\" }}"
        TRAKT_CLIENT_ID: "{{ index . \"TRAKT_CLIENT_ID\" | default \"\" }}"
        TRAKT_CLIENT_SECRET: "{{ index . \"TRAKT_CLIENT_SECRET\" | default \"\" }}"
        TRAKT_ACCESS_TOKEN: "{{ index . \"TRAKT_ACCESS_TOKEN\" | default \"\" }}"
        TRAKT_REFRESH_TOKEN: "{{ index . \"TRAKT_REFRESH_TOKEN\" | default \"\" }}"
        TRAKT_EXPIRES_IN: "{{ index . \"TRAKT_EXPIRES_IN\" | default \"\" }}"
        TRAKT_CREATED_AT: "{{ index . \"TRAKT_CREATED_AT\" | default \"\" }}"
  dataFrom:
    - extract:
        key: kometa
    - extract:
        key: bitmagnet