---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kometa-secret
    creationPolicy: Owner
    template:
      data:
        KOMETA_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        KOMETA_TMDB_API_KEY: "{{ .TMDB_API_KEY }}"
        KOMETA_OMDB_API_KEY: "{{ .OMDB_API_KEY }}"
        KOMETA_TRAKT_CLIENT_ID: "{{ .TRAKT_CLIENT_ID }}"
        KOMETA_TRAKT_CLIENT_SECRET: "{{ .TRAKT_CLIENT_SECRET }}"
        KOMETA_TRAKT_ACCESS_TOKEN: "{{ .TRAKT_ACCESS_TOKEN }}"
        KOMETA_TRAKT_REFRESH_TOKEN: "{{ .TRAKT_REFRESH_TOKEN }}"
        KOMETA_TRAKT_EXPIRES_IN: "{{ .TRAKT_EXPIRES_IN }}"
        KOMETA_TRAKT_CREATED_AT: "{{ .TRAKT_CREATED_AT }}"
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: /kometa/PLEX_TOKEN
    - secretKey: TMDB_API_KEY
      remoteRef:
        key: /bitmagnet/TMDB_API_KEY
    - secretKey: OMDB_API_KEY
      remoteRef:
        key: /kometa/OMDB_API_KEY
    - secretKey: TRAKT_CLIENT_ID
      remoteRef:
        key: /kometa/TRAKT_CLIENT_ID
    - secretKey: TRAKT_CLIENT_SECRET
      remoteRef:
        key: /kometa/TRAKT_CLIENT_SECRET
    - secretKey: TRAKT_ACCESS_TOKEN
      remoteRef:
        key: /kometa/TRAKT_ACCESS_TOKEN
    - secretKey: TRAKT_REFRESH_TOKEN
      remoteRef:
        key: /kometa/TRAKT_REFRESH_TOKEN
    - secretKey: TRAKT_EXPIRES_IN
      remoteRef:
        key: /kometa/TRAKT_EXPIRES_IN
    - secretKey: TRAKT_CREATED_AT
      remoteRef:
        key: /kometa/TRAKT_CREATED_AT