---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umlautadaptarr
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: umlautadaptarr-secret
    creationPolicy: Owner
    template:
      data:
        SONARR__APIKEY: "{{ .API_KEY }}"
        SONARR__0__APIKEY: "{{ .API_KEY }}"
        RADARR__APIKEY: "{{ .API_KEY }}"
        RADARR__0__APIKEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: servarr
