---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: plex-dst
spec:
  trigger:
    manual: restore-once
  restic:
    repository: plex-volsync-secret
    destinationPVC: plex
    copyMethod: Direct
    accessModes:
      - ReadWriteOnce
    cacheCapacity: 25Gi
    cacheStorageClassName: ceph-block
    cacheAccessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    cleanupCachePVC: true
    enableFileDeletion: true
