---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-volsync-restore
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: plex-volsync-secret
    template:
      data:
        RESTIC_REPOSITORY: "{{ .REPOSITORY_TEMPLATE }}/plex"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        RCLONE_CONFIG_BACKUP_TYPE: sftp
        RCLONE_CONFIG_BACKUP_HOST: "{{ .BACKUP_HOST }}"
        RCLONE_CONFIG_BACKUP_USER: "{{ .BACKUP_USER }}"
        RCLONE_CONFIG_BACKUP_KEY_PEM: "{{ .KEY_PEM }}"
        RCLONE_CONFIG_BACKUP_SHELL_TYPE: unix
        RCLONE_CONFIG_BACKUP_MD5SUM_COMMAND: none
        RCLONE_CONFIG_BACKUP_SHA1SUM_COMMAND: none
  dataFrom:
    - extract:
        key: restic-netdynamics
