---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencloud
spec:
  chartRef:
    kind: OCIRepository
    name: opencloud
  interval: 30m
  driftDetection:
    mode: enabled
  values:
    controllers:
      opencloud:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
        initContainers:
          init-config:
            image:
              repository: docker.io/opencloudeu/opencloud-rolling
              tag: 5.1.0@sha256:6229e937e32e5e114ddac81af7e851fb9346a818c58a36b784529d5503530f93
            command:
              - /bin/sh
              - -c
              - test -f /etc/opencloud/opencloud.yaml || opencloud init --insecure=true
            envFrom:
              - secretRef:
                  name: opencloud-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        containers:
          opencloud:
            image:
              repository: docker.io/opencloudeu/opencloud-rolling
              tag: 5.1.0@sha256:6229e937e32e5e114ddac81af7e851fb9346a818c58a36b784529d5503530f93
            command:
              - opencloud
              - server
            env:
              IDM_CREATE_DEMO_USERS: false
              IDM_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: opencloud-secret
                    key: idm-admin-password
              OC_ENABLE_OCM: false
              OC_INSECURE: false
              OC_LOG_LEVEL: info
              OC_URL: https://opencloud.brauni.eu
              COLLABORA_DOMAIN: collabora.brauni.eu
              GATEWAY_GRPC_ADDR: 0.0.0.0:9142
              NATS_NATS_HOST: 0.0.0.0
              FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration
              GRAPH_AVAILABLE_ROLES: OpenCloud Admin,Space Admin,User,Guest,OpenCloud Editor
              PROXY_TLS: false
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1024Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          collaboration:
            image:
              repository: docker.io/opencloudeu/opencloud-rolling
              tag: 5.1.0@sha256:6229e937e32e5e114ddac81af7e851fb9346a818c58a36b784529d5503530f93
            command:
              - opencloud
              - collaboration
              - server
            env:
              COLLABORATION_APP_ADDR: https://collabora.brauni.eu
              COLLABORATION_APP_ICON: https://opencloud.brauni.eu/apps/files/img/app.svg
              COLLABORATION_APP_INSECURE: false
              COLLABORATION_APP_NAME: CollaboraOnline
              COLLABORATION_CS3API_DATAGATEWAY_INSECURE: false
              COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
              COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
              COLLABORATION_LOG_LEVEL: info
              COLLABORATION_WOPI_SRC: https://wopiserver.brauni.eu
              MICRO_REGISTRY: nats-js-kv
              MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
              OC_URL: https://opencloud.brauni.eu
              PRODUCT: Collabora
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          radicale:
            image:
              repository: docker.io/tomsquest/docker-radicale
              tag: latest@sha256:5d2c623f2cb306f8cc8d7d95d96f95e7eebf40b7ae366307f95c67df80be1e33
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          collabora:
            image:
              repository: docker.io/collabora/code
              tag: 24.04.13.2.1@sha256:f4e34e4ee70f4462a37f7f97fd7f44fe4b8d8f4845de32a22ce0ff58832277ff
            env:
              DONT_GEN_SSL_CERT: "YES"
              domain: collabora\\.brauni\\.eu
              extra_params: --o:ssl.enable=false --o:ssl.termination=true --o:logging.level=warning --o:net.frame_ancestors=https://*.brauni.eu
              username:
                valueFrom:
                  secretKeyRef:
                    name: opencloud-secret
                    key: collabora-username
              password:
                valueFrom:
                  secretKeyRef:
                    name: opencloud-secret
                    key: collabora-password
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              runAsNonRoot: false
              capabilities:
                add:
                  - MKNOD
                  - SYS_CHROOT
                  - FOWNER
                  - CHOWN
    service:
      app:
        controller: opencloud
        ports:
          http:
            port: 9200
      wopiserver:
        controller: opencloud
        ports:
          http:
            port: 9300
      collabora:
        controller: opencloud
        ports:
          http:
            port: 9980
    persistence:
      data:
        existingClaim: opencloud
        globalMounts:
          - path: /var/lib/opencloud
            subPath: data
          - path: /etc/opencloud
            subPath: config
      config:
        type: configMap
        identifier: config
        advancedMounts:
          opencloud:
            opencloud:
              - path: /etc/opencloud/proxy.yaml
                subPath: proxy.yaml
            radicale:
              - path: /etc/radicale/config
                subPath: radicale.config
      radicale:
        existingClaim: opencloud
        advancedMounts:
          opencloud:
            radicale:
              - path: /var/lib/radicale
                subPath: radicale
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
    route:
      app:
        hostnames:
          - files.brauni.eu
          - opencloud.brauni.eu
        parentRefs:
          - name: envoy-brauni-eu-public
            namespace: network
            sectionName: https
      collabora:
        hostnames:
          - collabora.brauni.eu
        parentRefs:
          - name: envoy-brauni-eu-public
            namespace: network
            sectionName: https
      wopiserver:
        hostnames:
          - wopiserver.brauni.eu
        parentRefs:
          - name: envoy-brauni-eu-public
            namespace: network
            sectionName: https
    configMaps:
      config:
        data:
          proxy.yaml: |-
            additional_policies:
              - name: "calendar"
                routes:
                  - endpoint: "/dav/spaces/[^/]+/calendars"
                    backend: "http://127.0.0.1:5232"
                  - endpoint: "/dav/spaces/[^/]+/addressbooks"
                    backend: "http://127.0.0.1:5232"
              - name: "collaboration"
                routes:
                  - endpoint: "/cool"
                    backend: "http://127.0.0.1:9300"
                  - endpoint: "/browser"
                    backend: "http://127.0.0.1:9300"
                  - endpoint: "/hosting/discovery"
                    backend: "http://127.0.0.1:9300"
          radicale.config: |-
            [server]
            hosts = 0.0.0.0:5232

            [auth]
            type = http_x_remote_user

            [storage]
            filesystem_folder = /var/lib/radicale/collections
