---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-rclone
spec:
  chartRef:
    kind: OCIRepository
    name: csi-rclone
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    image:
      rclone:
        tag: v0.4.9
    feature:
      enableInlineVolume: true
    node:
      resources:
        rclone:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 12Gi
      cache:
        enabled: true
        hostPath: /var/mnt/local-hostpath/rclone-cache
        mountPath: /var/lib/rclone-cache
      metrics:
        enabled: true
        service:
          enabled: true
        serviceMonitor:
          enabled: true
        dashboard:
          enabled: true
          namespace: observability
