---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: csi-rclone
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.5.0
    digest: sha256:72e94539abeb78b31a4d46ade06bbe99e23216181e79e318dd2df84c6cf6794a
  url: oci://ghcr.io/veloxpack/charts/csi-driver-rclone
