---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rclone-decypharr
provisioner: rclone.csi.veloxpack.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - allow-non-empty=true
  - allow-other=true
  - uid=1000
  - gid=1000
  - vfs-cache-mode=full
  - vfs-cache-max-age=100h
  - vfs-cache-max-size=20G
  - async-read=true
  - vfs-read-ahead=128M
  - vfs-read-chunk-size=128M
  - vfs-read-chunk-size-limit=256M
  - no-modtime=true
  - no-checksum=true
  - read-only=true
  - use-mmap=true
  - buffer-size=64M
  - dir-cache-time=10s
  - contimeout=5m
parameters:
  remote: decypharr
  remotePath: "/"
  configData: |
    [decypharr]
    type = webdav
    url = http://decypharr.media.svc.cluster.local:8282/webdav
    vendor = other
