---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: /cloudnative-pg/USERNAME
    - secretKey: password
      remoteRef:
        key: /cloudnative-pg/PASSWORD
