---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: radarr4k4k-brauni-dev
spec:
  hostnames:
    - radarr4k.brauni.dev
  parentRefs:
    - name: envoy-brauni-dev-public
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: radarr4k
          port: 80
---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: radarr4k4k-riki-boo
spec:
  hostnames:
    - radarr4k.riki.boo
  parentRefs:
    - name: envoy-riki-boo-public
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: radarr4k
          port: 80
