---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: altmount-sync-helper
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: altmount-sync-helper-secret
    creationPolicy: Owner
    template:
      data:
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: /sync-helper/PLEX_TOKEN
