---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: niks3
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: niks3-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        api-token: '{{ .API_TOKEN | default (index . "NIKS3_API_TOKEN") | default (index . "api-token") | default (index . "api_token") | default (index . "api token") | default (index . "API Token") | default (index . "token") | default (index . "password") }}'
        signing-key: '{{ .SIGNING_KEY | default (index . "NIKS3_SIGNING_KEY") | default (index . "NIKS3_SIGN_KEY") | default (index . "signing-key") | default (index . "signing_key") | default (index . "signing key") | default (index . "Signing Key") }}'
  dataFrom:
    - extract:
        key: niks3
