---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/objectbucket.io/objectbucketclaim_v1alpha1.json
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: niks3-bucket
spec:
  bucketName: niks3
  storageClassName: ceph-bucket
