---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencloud
spec:
  chartRef:
    kind: OCIRepository
    name: opencloud
  interval: 30m
  driftDetection:
    mode: enabled
  values:
    controllers:
      opencloud:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
        initContainers:
          init-config:
            image:
              repository: docker.io/opencloudeu/opencloud-rolling
              tag: 6.1.0@sha256:235b5d988729aa821bd068bbdc60175270b05bd5fefa77b6d0e2ec5aeadccd0b
            command:
              - /bin/sh
              - -c
              - test -f /etc/opencloud/opencloud.yaml || opencloud init --insecure=true
            envFrom:
              - secretRef:
                  name: opencloud-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        containers:
          opencloud:
            image:
              repository: docker.io/opencloudeu/opencloud-rolling
              tag: 6.1.0@sha256:235b5d988729aa821bd068bbdc60175270b05bd5fefa77b6d0e2ec5aeadccd0b
            command:
              - opencloud
              - server
            env:
              IDM_CREATE_DEMO_USERS: false
              IDM_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: opencloud-secret
                    key: idm-admin-password
              OC_ENABLE_OCM: false
              OC_INSECURE: false
              OC_LOG_LEVEL: info
              OC_URL: https://opencloud.brauni.dev
              PROXY_TLS: false
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1024Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          radicale:
            image:
              repository: docker.io/opencloudeu/radicale
              tag: latest@sha256:38f824a38414e320b4469a614a98c2e13612158148225c4189e500553eeb78ae
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      app:
        controller: opencloud
        ports:
          http:
            port: 9200
    persistence:
      data:
        existingClaim: opencloud
        globalMounts:
          - path: /var/lib/opencloud
            subPath: data
          - path: /etc/opencloud
            subPath: config
      config:
        type: configMap
        identifier: config
        advancedMounts:
          opencloud:
            opencloud:
              - path: /etc/opencloud/proxy.yaml
                subPath: proxy.yaml
            radicale:
              - path: /etc/radicale/config
                subPath: radicale.config
      radicale:
        existingClaim: opencloud
        advancedMounts:
          opencloud:
            radicale:
              - path: /var/lib/radicale
                subPath: radicale
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Selfhosted
          gethomepage.dev/name: OpenCloud
          gethomepage.dev/pod-selector: app.kubernetes.io/name=opencloud
          gethomepage.dev/icon: https://opencloud.brauni.dev/themes/opencloud/assets/logo.svg
          gethomepage.dev/href: https://opencloud.brauni.dev
        hostnames:
          - files.brauni.dev
          - opencloud.brauni.dev
        parentRefs:
          - name: envoy-brauni-dev-public
            namespace: network
            sectionName: https
    configMaps:
      config:
        data:
          proxy.yaml: |-
            additional_policies:
              - name: default
                routes:
                  - endpoint: /caldav/
                    backend: "http://127.0.0.1:5232"
                    remote_user_header: X-Remote-User
                    skip_x_access_token: true
                    additional_headers:
                      - X-Script-Name: /caldav
                  - endpoint: /.well-known/caldav
                    backend: "http://127.0.0.1:5232"
                    remote_user_header: X-Remote-User
                    skip_x_access_token: true
                    additional_headers:
                      - X-Script-Name: /caldav
                  - endpoint: /carddav/
                    backend: "http://127.0.0.1:5232"
                    remote_user_header: X-Remote-User
                    skip_x_access_token: true
                    additional_headers:
                      - X-Script-Name: /carddav
                  - endpoint: /.well-known/carddav
                    backend: "http://127.0.0.1:5232"
                    remote_user_header: X-Remote-User
                    skip_x_access_token: true
                    additional_headers:
                      - X-Script-Name: /carddav
          radicale.config: |-
            [server]
            hosts = 0.0.0.0:5232

            [auth]
            type = http_x_remote_user

            [storage]
            filesystem_folder = /var/lib/radicale/collections
            predefined_collections = {
              "def-addressbook": {
                "D:displayname": "Personal Address Book",
                "tag": "VADDRESSBOOK"
              },
              "def-calendar": {
                "C:supported-calendar-component-set": "VEVENT,VJOURNAL,VTODO",
                "D:displayname": "Personal Calendar",
                "tag": "VCALENDAR"
              }
              }
