---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kguardian
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.17.2
    digest: sha256:264a427f35cea51c59203123b8317eeef3db069b178c1238da1ed828e439a110
  url: oci://ghcr.io/kguardian-dev/charts/kguardian
