---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kguardian
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.21.2
    digest: sha256:8da4a4f958742a2d6b9f5a6126fb8675eda89d74b63ee58f2524f49ad3ba514e
  url: oci://ghcr.io/kguardian-dev/charts/kguardian
