---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kguardian
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.17.3
    digest: sha256:74ddcfb90214f63da17ab1b86d3eb41ee495608f7effd58e7f53dba9c045a6d9
  url: oci://ghcr.io/kguardian-dev/charts/kguardian
