---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-rclone
spec:
  accessModes:
    - ${RCLONE_ACCESSMODES:=ReadOnlyMany}
  resources:
    requests:
      storage: ${RCLONE_CAPACITY:=1Gi}
  storageClassName: ${RCLONE_STORAGECLASS:=rclone-decypharr}
