---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: tinyauth-securitypolicy-backendrefs
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: flux-system
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: kguardian
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: observability
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: media
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: volsync-system
  to:
    - group: ""
      kind: Service
      name: tinyauth-riki-boo
    - group: ""
      kind: Service
      name: tinyauth-brauni-eu
    - group: ""
      kind: Service
      name: tinyauth-brauni-dev
