---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: decypharr-rclone
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rclone-decypharr
