---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tinyauth-brauni-dev
spec:
  chartRef:
    kind: OCIRepository
    name: tinyauth-brauni-dev
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controllers:
      tinyauth-brauni-dev:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/steveiliop56/tinyauth
              tag: v5.0.5-beta.3-distroless@sha256:c72d8bffdea3f86e6b9444737c23e14f78a1d260598d5ccb120dea73870828c4
            env:
              TINYAUTH_APPURL: https://auth.brauni.dev
              TINYAUTH_ANALYTICS_ENABLED: false
              TINYAUTH_AUTH_SECURECOOKIE: true
              TINYAUTH_AUTH_SESSIONEXPIRY: 604800
              TINYAUTH_RESOURCES_PATH: /data/resources
              TINYAUTH_DATABASE_PATH: /data/tinyauth.db
              TINYAUTH_AUTH_TRUSTEDPROXIES: 10.42.0.0/16
            envFrom:
              - secretRef:
                  name: tinyauth-brauni-dev-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/healthz
                    port: &port 3000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: tinyauth-brauni-dev
        ports:
          http:
            port: *port
    route:
      brauni-dev:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Network
          gethomepage.dev/name: TinyAuth (brauni.dev)
          gethomepage.dev/pod-selector: app.kubernetes.io/name=tinyauth-brauni-dev
          gethomepage.dev/icon: mdi-lock-check
        hostnames:
          - auth.brauni.dev
        parentRefs:
          - name: envoy-brauni-dev-public
            namespace: network
            sectionName: https
    persistence:
      data:
        type: emptyDir
        advancedMounts:
          tinyauth-brauni-dev:
            app:
              - path: /data
