---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    csi:
      serviceMonitor:
        enabled: true
    image:
      repository: ghcr.io/rook/ceph
      tag: v1.20.0@sha256:5e543abbab51acb0818f5b319bbd5e7ad435bfd8e011d4f532e6b9588ce6157d
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 100m # unchangable
        memory: 128Mi # unchangable
      limits: {}
