---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    csi:
      serviceMonitor:
        enabled: true
    image:
      repository: ghcr.io/rook/ceph
      tag: v1.20.2@sha256:a642e07d4d0b4d02214e435337c7f5d3f5154369270ea5180de9d5d5d9d965c2
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 100m # unchangable
        memory: 128Mi # unchangable
      limits: {}
