---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    csi:
      enableRbdDriver: true
      cephFSKernelMountOptions: ms_mode=prefer-crc
      # NOTE: Enable the driver and shapshotter if you want to use CephFS
      enableCephfsDriver: true
      enableCephfsSnapshotter: true
      enableLiveness: true
      serviceMonitor:
        enabled: true
    image:
      repository: ghcr.io/rook/ceph
      tag: v1.19.4@sha256:f0f307d7fce0ba2bc60d15e446b9fafddf1153492398fd653d10708f9874bf31
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 100m # unchangable
        memory: 128Mi # unchangable
      limits: {}
