---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stremthru
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: stremthru-secret
    creationPolicy: Owner
    template:
      data:
        STREMTHRU_AUTH: "{{ .STREMTHRU_AUTH }}"
        STREMTHRU_AUTH_ADMIN: "{{ .STREMTHRU_AUTH_ADMIN }}"
        STREMTHRU_INTEGRATION_GITHUB_USER: "{{ .STREMTHRU_INTEGRATION_GITHUB_USER }}"
        STREMTHRU_INTEGRATION_GITHUB_TOKEN: "{{ .STREMTHRU_INTEGRATION_GITHUB_TOKEN }}"
        STREMTHRU_INTEGRATION_TMDB_ACCESS_TOKEN: "{{ .STREMTHRU_INTEGRATION_TMDB_ACCESS_TOKEN }}"
        STREMTHRU_INTEGRATION_TVDB_API_KEY: "{{ .STREMTHRU_INTEGRATION_TVDB_API_KEY }}"
        STREMTHRU_VAULT_SECRET: "{{ .STREMTHRU_VAULT_SECRET }}"
  data:
    - secretKey: STREMTHRU_AUTH
      remoteRef:
        key: /stremthru/STREMTHRU_AUTH
    - secretKey: STREMTHRU_AUTH_ADMIN
      remoteRef:
        key: /stremthru/STREMTHRU_AUTH_ADMIN
    - secretKey: STREMTHRU_INTEGRATION_GITHUB_USER
      remoteRef:
        key: /stremthru/STREMTHRU_INTEGRATION_GITHUB_USER
    - secretKey: STREMTHRU_INTEGRATION_GITHUB_TOKEN
      remoteRef:
        key: /stremthru/STREMTHRU_INTEGRATION_GITHUB_TOKEN
    - secretKey: STREMTHRU_INTEGRATION_TMDB_ACCESS_TOKEN
      remoteRef:
        key: /stremthru/STREMTHRU_INTEGRATION_TMDB_ACCESS_TOKEN
    - secretKey: STREMTHRU_INTEGRATION_TVDB_API_KEY
      remoteRef:
        key: /stremthru/STREMTHRU_INTEGRATION_TVDB_API_KEY
    - secretKey: STREMTHRU_VAULT_SECRET
      remoteRef:
        key: /stremthru/STREMTHRU_VAULT_SECRET
