---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stremthru
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: stremthru-secret
    creationPolicy: Owner
    template:
      data:
        STREMTHRU_AUTH: "{{ .STREMTHRU_AUTH }}"
        STREMTHRU_AUTH_ADMIN: "{{ .STREMTHRU_AUTH_ADMIN }}"
        STREMTHRU_VAULT_SECRET: "{{ .STREMTHRU_VAULT_SECRET }}"
  dataFrom:
    - extract:
        key: stremthru
