apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      secretsScope:
        environmentSlug: prod
        projectSlug: ovh-ops-u1ua
        secretsPath: /
        recursive: true
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-clientId
            namespace: external-secrets
          clientSecret:
            key: clientSecret
            name: infisical-clientSecret
            namespace: external-secrets
