apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-universal-auth-credentials
            key: clientId
            namespace: external-secrets
          clientSecret:
            name: infisical-universal-auth-credentials
            key: clientSecret
            namespace: external-secrets
      secretsScope:
        environmentSlug: prod
        projectSlug: ovh-ops-u1ua
        secretsPath: /
        recursive: true