---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repair
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: repair-secret
    creationPolicy: Owner
    template:
      data:
        arrs.json: |
          [
            { "name": "radarr",   "url": "http://radarr.media.svc.cluster.local:80",   "api_key": "{{ .API_KEY }}", "type": "radarr" },
            { "name": "sonarr",   "url": "http://sonarr.media.svc.cluster.local:80",   "api_key": "{{ .API_KEY }}", "type": "sonarr" },
            { "name": "radarr4k", "url": "http://radarr4k.media.svc.cluster.local:80", "api_key": "{{ .API_KEY }}", "type": "radarr" },
            { "name": "sonarr4k", "url": "http://sonarr4k.media.svc.cluster.local:80", "api_key": "{{ .API_KEY }}", "type": "sonarr" }
          ]
  dataFrom:
    - extract:
        key: servarr
