---
# yaml-language-server: $schema=https://kubernetes-schemas.brauni.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technitium-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: technitium-dns-secret
    template:
      data:
        EXTERNAL_DNS_RFC2136_TSIG_SECRET: "{{ .envoy_internal_dns }}"
  data:
    - secretKey: envoy_internal_dns
      remoteRef:
        key: /technitium/ENVOY_INTERNAL_DNS
