---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/kopiur
  dependsOn:
    - name: kopiur-repository
      namespace: kopiur-system
    - name: openebs
      namespace: openebs-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: symlinks
      namespace: media
  interval: 1h
  path: ./kubernetes/apps/media/plex/app
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CAPACITY: 25Gi
      KOPIUR_ON_MISSING_SNAPSHOT: Fail
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
